// console.log(2);
// var a = 2;
// let hello = (a) => a;

// const a = [1, 2, 3];

// a[1] = 10; được
// a = [1,2,3] lỗi
console.log(a);

try {
  console.log(test());
} catch (err) {
  console.log(err.message);
} finally {
  console.log("Cảm ơn bạn đã sử dụng dịch vụ");
}

console.log("hihi");
